class AppStrings {
  // 🔹 English translations
  static const Map<String, String> en = {
    'app_title': 'Punjab Bus Tracker',
    'routes': 'Routes',
    'notifications': 'Notifications',
    'liked_buses': 'Liked Buses',
    'menu': 'Menu',
    'language_selection': 'Language Selection',
    'settings': 'Settings',
    'profile': 'Profile',
    'logout': 'Logout',
    'login': 'Login',
    'register': 'Register',
    'username': 'Username',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'email': 'Email',
    'phone_number': 'Phone Number',
    'save': 'Save',
    'cancel': 'Cancel',
    'back': 'Back',
    'find_buses': 'Find Buses',
    'from_city': 'From City',
    'to_city': 'To City',
    'find_buses_button': 'Find Buses',
    'no_buses_found': 'No buses found',
    'bus': 'Bus',
    'from': 'From',
    'to': 'To',
    'arrival_time': 'Arrival Time',
    'departure_time': 'Departure Time',
    'estimated_time': 'Estimated Time',
    'bus_arriving': 'Your bus is arriving soon',
    'bus_delayed': 'Your bus is delayed by {minutes} minutes',
    'bus_departed': 'Bus has already departed',
    'bus_cancelled': 'This bus has been cancelled',
    'select_language': 'Select Language',
    'choose_your_preferred_language': 'Choose your preferred language',
    'language_changed': 'Language changed to {language}',
    'current_language': 'Current Language',
    'loading': 'Loading...',
    'error': 'Error',
    'network_error': 'Network connection failed',
    'server_error': 'Server not responding',
    'retry': 'Retry',
    'refresh': 'Refresh',
    'success': 'Success',
    'failed': 'Failed',
    'yes': 'Yes',
    'no': 'No',
    'ok': 'OK',
    'done': 'Done',
    'exit_app': 'Do you really want to exit the app?',
    'alert_times': '15, 10, 5 min before arrival',
    'bus_number': 'Bus {busNumber}',
    'bus_route': '{fromCity} → {toCity}',
    'arrives_at': 'Arrives at {arrivalTime}',
    'multiple_alerts_scheduled': 'Multiple alerts scheduled:',
    'alert_time': '{time}',
    'from_arrival': '{fromArrival}',
    'to_arrival': '{toArrival}',
    'alerts_scheduled': 'Alerts: {alerts}',
    'alerts_none': 'Alerts: none',
    'cancel_notification_confirm':
        'Are you sure you want to cancel the notification for Bus {busNumber}?',
    'notification_cancelled': 'Notification for Bus {busNumber} cancelled',
    'clear_all_confirm':
        'Are you sure you want to cancel all scheduled notifications?',
    'delete_notification': 'Delete Notification',
    'delete_notification_confirm':
        'Delete scheduled notifications for Bus {busNumber}?',
    'deleted_notifications': 'Deleted notifications for Bus {busNumber}',
    'error_deleting': 'Error deleting: {error}',
    'delete_all_notifications': 'Delete all notifications?',
    'remove_all_scheduled_alerts': 'This will remove all scheduled bus alerts.',
    'remove_count_scheduled_alerts':
        'This will remove {count} scheduled bus alerts.',
    'all_notifications_deleted': 'All notifications deleted',
    'error_deleting_all': 'Error deleting all: {error}',
  };

  // 🔹 Hindi translations
  static const Map<String, String> hi = {
    'app_title': 'पंजाब बस ट्रैकर',
    'routes': 'रूट्स',
    'notifications': 'सूचनाएं',
    'liked_buses': 'पसंदीदा बसें',
    'menu': 'मेनू',
    'language_selection': 'भाषा चयन',
    'settings': 'सेटिंग्स',
    'profile': 'प्रोफ़ाइल',
    'logout': 'लॉगआउट',
    'login': 'लॉगिन',
    'register': 'पंजीकरण',
    'username': 'उपयोगकर्ता नाम',
    'password': 'पासवर्ड',
    'confirm_password': 'पासवर्ड की पुष्टि करें',
    'email': 'ईमेल',
    'phone_number': 'फ़ोन नंबर',
    'save': 'सेव करें',
    'cancel': 'रद्द करें',
    'back': 'वापस',
    'find_buses': 'बसें खोजें',
    'from_city': 'शहर से',
    'to_city': 'शहर तक',
    'find_buses_button': 'बसें खोजें',
    'no_buses_found': 'कोई बस नहीं मिली',
    'bus': 'बस',
    'from': 'से',
    'to': 'तक',
    'arrival_time': 'आगमन समय',
    'departure_time': 'प्रस्थान समय',
    'estimated_time': 'अनुमानित समय',
    'bus_arriving': 'आपकी बस जल्द ही आ रही है',
    'bus_delayed': 'आपकी बस {minutes} मिनट विलंबित है',
    'bus_departed': 'बस पहले ही प्रस्थान कर चुकी है',
    'bus_cancelled': 'यह बस रद्द कर दी गई है',
    'select_language': 'भाषा चुनें',
    'choose_your_preferred_language': 'अपनी पसंदीदा भाषा चुनें',
    'language_changed': 'भाषा {language} में बदल दी गई',
    'current_language': 'वर्तमान भाषा',
    'loading': 'लोड हो रहा है...',
    'error': 'त्रुटि',
    'network_error': 'नेटवर्क कनेक्शन विफल',
    'server_error': 'सर्वर प्रतिक्रिया नहीं दे रहा',
    'retry': 'पुनः प्रयास करें',
    'refresh': 'रिफ्रेश करें',
    'success': 'सफलता',
    'failed': 'विफल',
    'yes': 'हां',
    'no': 'नहीं',
    'ok': 'ठीक',
    'done': 'पूर्ण',
    'exit_app': 'क्या आप वास्तव में ऐप से बाहर निकलना चाहते हैं?',
  };

  // 🔹 Tamil translations
  static const Map<String, String> ta = {
    'app_title': 'பஞ்சாப் பஸ் டிராக்கர்',
    'routes': 'வழிகள்',
    'notifications': 'அறிவிப்புகள்',
    'liked_buses': 'விருப்பமான பஸ்கள்',
    'menu': 'மெனு',
    'language_selection': 'மொழி தேர்வு',
    'settings': 'அமைப்புகள்',
    'profile': 'சுயவிவரம்',
    'logout': 'வெளியேறு',
    'login': 'உள்நுழை',
    'register': 'பதிவு செய்',
    'username': 'பயனர் பெயர்',
    'password': 'கடவுச்சொல்',
    'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்து',
    'email': 'மின்னஞ்சல்',
    'phone_number': 'தொலைபேசி எண்',
    'save': 'சேமி',
    'cancel': 'ரத்து செய்',
    'back': 'பின் செல்',
    'find_buses': 'பஸ்களைக் கண்டறியவும்',
    'from_city': 'நகரத்திலிருந்து',
    'to_city': 'நகரத்திற்கு',
    'find_buses_button': 'பஸ்களைக் கண்டறியவும்',
    'no_buses_found': 'பஸ்கள் எதுவும் கிடைக்கவில்லை',
    'bus': 'பஸ்',
    'from': 'இருந்து',
    'to': 'வரை',
    'arrival_time': 'வருகை நேரம்',
    'departure_time': 'புறப்படும் நேரம்',
    'estimated_time': 'மதிப்பிடப்பட்ட நேரம்',
    'bus_arriving': 'உங்கள் பஸ் விரைவில் வருகிறது',
    'bus_delayed': 'உங்கள் பஸ் {minutes} நிமிடங்கள் தாமதமாகிறது',
    'bus_departed': 'பஸ் ஏற்கனவே புறப்பட்டுள்ளது',
    'bus_cancelled': 'இந்த பஸ் ரத்து செய்யப்பட்டது',
    'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    'choose_your_preferred_language':
        'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
    'language_changed': 'மொழி {language} க்கு மாற்றப்பட்டது',
    'current_language': 'தற்போதைய மொழி',
    'loading': 'ஏற்றப்படுகிறது...',
    'error': 'பிழை',
    'network_error': 'பிணைய இணைப்பு தோல்வியடைந்தது',
    'server_error': 'சர்வர் பதிலளிக்கவில்லை',
    'retry': 'மீண்டும் முயற்சிக்கவும்',
    'refresh': 'புதுப்பிக்கவும்',
    'success': 'வெற்றி',
    'failed': 'தோல்வி',
    'yes': 'ஆம்',
    'no': 'இல்லை',
    'ok': 'சரி',
    'done': 'முடிந்தது',
    'exit_app': 'உண்மையிலேயே பயன்பாட்டை வெளியேற விரும்புகிறீர்களா?',
  };

  // 🔹 Punjabi translations
  static const Map<String, String> pa = {
    'app_title': 'ਪੰਜਾਬ ਬਸ ਟ੍ਰੈਕਰ',
    'routes': 'ਰੂਟ',
    'notifications': 'ਸੂਚਨਾਵਾਂ',
    'liked_buses': 'ਪਸੰਦੀਦਾ ਬੱਸਾਂ',
    'menu': 'ਮੇਨੂ',
    'language_selection': 'ਭਾਸ਼ਾ ਚੋਣ',
    'settings': 'ਸੈਟਿੰਗਜ਼',
    'profile': 'ਪ੍ਰੋਫ਼ਾਈਲ',
    'logout': 'ਲਾੱਗ ਆਊਟ',
    'login': 'ਲਾਗਇਨ',
    'register': 'ਰਜਿਸਟਰ',
    'username': 'ਯੂਜ਼ਰ ਨਾਮ',
    'password': 'ਪਾਸਵਰਡ',
    'confirm_password': 'ਪਾਸਵਰਡ ਪੁਸ਼ਟੀ ਕਰੋ',
    'email': 'ਈਮੇਲ',
    'phone_number': 'ਫੋਨ ਨੰਬਰ',
    'save': 'ਸੰਭਾਲੋ',
    'cancel': 'ਰੱਦ ਕਰੋ',
    'back': 'ਵਾਪਸ',
    'find_buses': 'ਬੱਸਾਂ ਲੱਭੋ',
    'from_city': 'ਸ਼ਹਿਰ ਤੋਂ',
    'to_city': 'ਸ਼ਹਿਰ ਤੱਕ',
    'find_buses_button': 'ਬੱਸਾਂ ਲੱਭੋ',
    'no_buses_found': 'ਕੋਈ ਬੱਸ ਨਹੀਂ ਮਿਲੀ',
    'bus': 'ਬੱਸ',
    'from': 'ਤੋਂ',
    'to': 'ਤੱਕ',
    'arrival_time': 'ਪਹੁੰਚਣ ਦਾ ਸਮਾਂ',
    'departure_time': 'ਰਵਾਨਗੀ ਦਾ ਸਮਾਂ',
    'estimated_time': 'ਅਨੁਮਾਨਿਤ ਸਮਾਂ',
    'bus_arriving': 'ਤੁਹਾਡੀ ਬੱਸ ਜਲਦੀ ਹੀ ਆ ਰਹੀ ਹੈ',
    'bus_delayed': 'ਤੁਹਾਡੀ ਬੱਸ {minutes} ਮਿੰਟ ਦੇ ਲਈ ਦੇਰੀ ਨਾਲ ਹੈ',
    'bus_departed': 'ਬੱਸ ਪਹਿਲਾਂ ਹੀ ਰਵਾਨਾ ਹੋ ਚੁਕੀ ਹੈ',
    'bus_cancelled': 'ਇਹ ਬੱਸ ਰੱਦ ਕਰ ਦਿੱਤੀ ਗਈ ਹੈ',
    'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
    'choose_your_preferred_language': 'ਆਪਣੀ ਪਸੰਦ ਦੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    'language_changed': 'ਭਾਸ਼ਾ {language} ਵਿੱਚ ਬਦਲ ਗਈ',
    'current_language': 'ਮੌਜੂਦਾ ਭਾਸ਼ਾ',
    'loading': 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    'error': 'ਗਲਤੀ',
    'network_error': 'ਨੈੱਟਵਰਕ ਕਨੈਕਸ਼ਨ ਫੇਲ੍ਹ',
    'server_error': 'ਸਰਵਰ ਜਵਾਬ ਨਹੀਂ ਦੇ ਰਿਹਾ',
    'retry': 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    'refresh': 'ਨਵੀਂ ਕਰੋ',
    'success': 'ਸਫਲਤਾ',
    'failed': 'ਫੇਲ੍ਹ',
    'yes': 'ਹਾਂ',
    'no': 'ਨਹੀਂ',
    'ok': 'ਠੀਕ ਹੈ',
    'done': 'ਹੋ ਗਿਆ',
    'exit_app': 'ਕੀ ਤੁਸੀਂ ਵਾਸਤਵ ਵਿੱਚ ਐਪ ਤੋਂ ਬਾਹਰ ਨਿਕਲਣਾ ਚਾਹੁੰਦੇ ਹੋ?',
  };

  static Map<String, String> getTranslations(String languageCode) {
    switch (languageCode) {
      case 'hi':
        return hi;
      case 'ta':
        return ta;
      case 'pa':
        return pa;
      case 'en':
      default:
        return en;
    }
  }

  static String translate(
    String key,
    String languageCode, {
    Map<String, String>? params,
  }) {
    final translations = getTranslations(languageCode);
    String text = translations[key] ?? en[key] ?? key;

    if (params != null) {
      params.forEach((paramKey, value) {
        text = text.replaceAll('{$paramKey}', value);
      });
    }

    return text;
  }
}
