import '../models/bus.dart';

class BusRepository {
  static List<Bus> getBuses() {
    return [
      Bus(
        fromCity: "Surat",
        toCity: "Mumbai",
        busNumber: "B1001",
        fromArrival: "12:18 pm",
        toArrival: "02:46 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Bhopal",
        busNumber: "B1002",
        fromArrival: "12:45 pm",
        toArrival: "12:29 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Jaipur",
        busNumber: "B1003",
        fromArrival: "05:13 pm",
        toArrival: "09:33 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Indore",
        busNumber: "B1004",
        fromArrival: "05:31 pm",
        toArrival: "10:09 am",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Chennai",
        busNumber: "B1005",
        fromArrival: "09:04 pm",
        toArrival: "08:17 am",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Kochi",
        busNumber: "B1006",
        fromArrival: "08:08 pm",
        toArrival: "09:36 am",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Mumbai",
        busNumber: "B1007",
        fromArrival: "08:16 am",
        toArrival: "12:11 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Jaipur",
        busNumber: "B1008",
        fromArrival: "05:43 pm",
        toArrival: "07:17 am",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Coimbatore",
        busNumber: "B1009",
        fromArrival: "08:16 pm",
        toArrival: "09:55 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Coimbatore",
        busNumber: "B1010",
        fromArrival: "09:03 pm",
        toArrival: "06:12 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Indore",
        busNumber: "B1011",
        fromArrival: "10:47 pm",
        toArrival: "07:25 am",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Indore",
        busNumber: "B1012",
        fromArrival: "02:31 pm",
        toArrival: "05:05 am",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Mumbai",
        busNumber: "B1013",
        fromArrival: "10:04 am",
        toArrival: "10:24 am",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Agra",
        busNumber: "B1014",
        fromArrival: "06:58 pm",
        toArrival: "02:13 pm",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Surat",
        busNumber: "B1015",
        fromArrival: "05:10 am",
        toArrival: "10:17 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Trichy",
        busNumber: "B1016",
        fromArrival: "09:25 am",
        toArrival: "05:00 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Nagpur",
        busNumber: "B1017",
        fromArrival: "08:25 pm",
        toArrival: "10:20 pm",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Lucknow",
        busNumber: "B1018",
        fromArrival: "07:47 am",
        toArrival: "06:18 am",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Coimbatore",
        busNumber: "B1019",
        fromArrival: "08:46 pm",
        toArrival: "07:32 pm",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Kochi",
        busNumber: "B1020",
        fromArrival: "09:49 pm",
        toArrival: "10:36 am",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Bhopal",
        busNumber: "B1021",
        fromArrival: "12:14 pm",
        toArrival: "05:15 pm",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Goa",
        busNumber: "B1022",
        fromArrival: "10:39 am",
        toArrival: "10:11 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Chandigarh",
        busNumber: "B1023",
        fromArrival: "10:21 pm",
        toArrival: "03:44 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Patna",
        busNumber: "B1024",
        fromArrival: "07:29 pm",
        toArrival: "06:52 am",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Mumbai",
        busNumber: "B1025",
        fromArrival: "01:03 pm",
        toArrival: "03:43 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Indore",
        busNumber: "B1026",
        fromArrival: "03:23 pm",
        toArrival: "05:28 am",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Trichy",
        busNumber: "B1027",
        fromArrival: "02:10 pm",
        toArrival: "10:26 am",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Mumbai",
        busNumber: "B1028",
        fromArrival: "05:16 pm",
        toArrival: "06:18 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Indore",
        busNumber: "B1029",
        fromArrival: "02:23 pm",
        toArrival: "09:56 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Jaipur",
        busNumber: "B1030",
        fromArrival: "05:58 pm",
        toArrival: "11:20 am",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Nagpur",
        busNumber: "B1031",
        fromArrival: "06:46 pm",
        toArrival: "12:31 pm",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Bangalore",
        busNumber: "B1032",
        fromArrival: "08:16 am",
        toArrival: "05:40 am",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Chennai",
        busNumber: "B1033",
        fromArrival: "05:11 am",
        toArrival: "10:19 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Patna",
        busNumber: "B1034",
        fromArrival: "09:42 am",
        toArrival: "10:49 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Surat",
        busNumber: "B1035",
        fromArrival: "03:37 pm",
        toArrival: "07:03 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Bhopal",
        busNumber: "B1036",
        fromArrival: "06:49 pm",
        toArrival: "05:07 pm",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Surat",
        busNumber: "B1037",
        fromArrival: "07:42 am",
        toArrival: "08:19 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Bhopal",
        busNumber: "B1038",
        fromArrival: "08:11 pm",
        toArrival: "07:30 am",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Lucknow",
        busNumber: "B1039",
        fromArrival: "04:20 pm",
        toArrival: "07:40 am",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Surat",
        busNumber: "B1040",
        fromArrival: "01:15 pm",
        toArrival: "11:55 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Indore",
        busNumber: "B1041",
        fromArrival: "08:33 am",
        toArrival: "07:34 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Chennai",
        busNumber: "B1042",
        fromArrival: "08:51 pm",
        toArrival: "04:57 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Indore",
        busNumber: "B1043",
        fromArrival: "01:48 pm",
        toArrival: "12:52 pm",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Goa",
        busNumber: "B1044",
        fromArrival: "10:29 am",
        toArrival: "10:21 am",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Kochi",
        busNumber: "B1045",
        fromArrival: "05:01 pm",
        toArrival: "02:48 pm",
      ),
      Bus(
        fromCity: "Indore",
        toCity: "Kochi",
        busNumber: "B1046",
        fromArrival: "04:14 pm",
        toArrival: "06:09 am",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Bhopal",
        busNumber: "B1047",
        fromArrival: "01:05 pm",
        toArrival: "06:59 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Mumbai",
        busNumber: "B1048",
        fromArrival: "06:07 am",
        toArrival: "10:38 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Patna",
        busNumber: "B1049",
        fromArrival: "09:20 pm",
        toArrival: "06:05 am",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Patna",
        busNumber: "B1050",
        fromArrival: "02:06 pm",
        toArrival: "07:01 am",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Agra",
        busNumber: "B1051",
        fromArrival: "12:06 pm",
        toArrival: "06:15 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Jaipur",
        busNumber: "B1052",
        fromArrival: "12:56 pm",
        toArrival: "08:23 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Goa",
        busNumber: "B1053",
        fromArrival: "12:45 pm",
        toArrival: "10:28 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Surat",
        busNumber: "B1054",
        fromArrival: "06:34 pm",
        toArrival: "03:48 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Agra",
        busNumber: "B1055",
        fromArrival: "02:26 pm",
        toArrival: "07:09 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Nagpur",
        busNumber: "B1056",
        fromArrival: "11:46 am",
        toArrival: "08:08 am",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Surat",
        busNumber: "B1057",
        fromArrival: "09:12 pm",
        toArrival: "08:26 am",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Jaipur",
        busNumber: "B1058",
        fromArrival: "03:18 pm",
        toArrival: "04:30 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Goa",
        busNumber: "B1059",
        fromArrival: "06:23 pm",
        toArrival: "06:25 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Goa",
        busNumber: "B1060",
        fromArrival: "02:55 pm",
        toArrival: "05:31 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Kochi",
        busNumber: "B1061",
        fromArrival: "10:16 am",
        toArrival: "05:53 am",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Kochi",
        busNumber: "B1062",
        fromArrival: "05:15 pm",
        toArrival: "05:26 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Kolkata",
        busNumber: "B1063",
        fromArrival: "05:53 pm",
        toArrival: "10:29 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Hyderabad",
        busNumber: "B1064",
        fromArrival: "07:34 pm",
        toArrival: "10:30 am",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Nagpur",
        busNumber: "B1065",
        fromArrival: "09:40 pm",
        toArrival: "06:21 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Kochi",
        busNumber: "B1066",
        fromArrival: "07:59 pm",
        toArrival: "07:28 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Patna",
        busNumber: "B1067",
        fromArrival: "04:41 pm",
        toArrival: "12:59 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Bhopal",
        busNumber: "B1068",
        fromArrival: "09:02 am",
        toArrival: "10:16 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Patna",
        busNumber: "B1069",
        fromArrival: "01:36 pm",
        toArrival: "08:23 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Jaipur",
        busNumber: "B1070",
        fromArrival: "07:35 am",
        toArrival: "08:45 pm",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Kochi",
        busNumber: "B1071",
        fromArrival: "05:12 pm",
        toArrival: "12:54 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Chandigarh",
        busNumber: "B1072",
        fromArrival: "09:30 pm",
        toArrival: "02:34 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Indore",
        busNumber: "B1073",
        fromArrival: "12:00 pm",
        toArrival: "09:17 am",
      ),
      Bus(
        fromCity: "Indore",
        toCity: "Delhi",
        busNumber: "B1074",
        fromArrival: "12:18 pm",
        toArrival: "12:16 pm",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Surat",
        busNumber: "B1075",
        fromArrival: "06:42 pm",
        toArrival: "05:18 am",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Madurai",
        busNumber: "B1076",
        fromArrival: "09:22 pm",
        toArrival: "04:57 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Agra",
        busNumber: "B1077",
        fromArrival: "09:18 pm",
        toArrival: "08:47 am",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Delhi",
        busNumber: "B1078",
        fromArrival: "10:21 am",
        toArrival: "12:14 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Delhi",
        busNumber: "B1079",
        fromArrival: "06:04 am",
        toArrival: "07:32 am",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Jaipur",
        busNumber: "B1080",
        fromArrival: "08:54 am",
        toArrival: "07:02 am",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Trichy",
        busNumber: "B1081",
        fromArrival: "10:28 pm",
        toArrival: "02:48 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Lucknow",
        busNumber: "B1082",
        fromArrival: "08:43 am",
        toArrival: "08:58 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Nagpur",
        busNumber: "B1083",
        fromArrival: "09:25 am",
        toArrival: "04:40 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Chennai",
        busNumber: "B1084",
        fromArrival: "04:44 pm",
        toArrival: "09:31 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Surat",
        busNumber: "B1085",
        fromArrival: "01:36 pm",
        toArrival: "10:28 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Goa",
        busNumber: "B1086",
        fromArrival: "03:14 pm",
        toArrival: "05:58 am",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Indore",
        busNumber: "B1087",
        fromArrival: "02:37 pm",
        toArrival: "11:01 am",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Agra",
        busNumber: "B1088",
        fromArrival: "05:25 pm",
        toArrival: "06:48 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Jaipur",
        busNumber: "B1089",
        fromArrival: "05:06 am",
        toArrival: "09:55 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Agra",
        busNumber: "B1090",
        fromArrival: "09:09 pm",
        toArrival: "10:11 pm",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Jaipur",
        busNumber: "B1091",
        fromArrival: "02:11 pm",
        toArrival: "08:08 am",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Mumbai",
        busNumber: "B1092",
        fromArrival: "01:40 pm",
        toArrival: "09:06 am",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Lucknow",
        busNumber: "B1093",
        fromArrival: "05:15 am",
        toArrival: "05:57 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Jaipur",
        busNumber: "B1094",
        fromArrival: "09:16 am",
        toArrival: "01:21 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Surat",
        busNumber: "B1095",
        fromArrival: "03:20 pm",
        toArrival: "06:57 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Chandigarh",
        busNumber: "B1096",
        fromArrival: "08:33 pm",
        toArrival: "04:23 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Bhopal",
        busNumber: "B1097",
        fromArrival: "01:33 pm",
        toArrival: "03:54 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Trichy",
        busNumber: "B1098",
        fromArrival: "06:32 am",
        toArrival: "10:54 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Bangalore",
        busNumber: "B1099",
        fromArrival: "05:25 pm",
        toArrival: "10:53 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Indore",
        busNumber: "B1100",
        fromArrival: "06:58 pm",
        toArrival: "10:56 am",
      ),
      Bus(
        fromCity: "Indore",
        toCity: "Chennai",
        busNumber: "B1101",
        fromArrival: "10:59 pm",
        toArrival: "09:04 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Bhopal",
        busNumber: "B1102",
        fromArrival: "09:36 pm",
        toArrival: "02:07 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Goa",
        busNumber: "B1103",
        fromArrival: "05:56 am",
        toArrival: "09:33 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Chennai",
        busNumber: "B1104",
        fromArrival: "09:01 am",
        toArrival: "06:01 am",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Goa",
        busNumber: "B1105",
        fromArrival: "09:17 am",
        toArrival: "06:03 am",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Kolkata",
        busNumber: "B1106",
        fromArrival: "05:10 am",
        toArrival: "06:46 am",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Patna",
        busNumber: "B1107",
        fromArrival: "05:18 pm",
        toArrival: "08:24 pm",
      ),
      Bus(
        fromCity: "Indore",
        toCity: "Hyderabad",
        busNumber: "B1108",
        fromArrival: "07:13 am",
        toArrival: "11:16 am",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Kolkata",
        busNumber: "B1109",
        fromArrival: "09:44 pm",
        toArrival: "09:17 am",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Bangalore",
        busNumber: "B1110",
        fromArrival: "10:56 pm",
        toArrival: "09:46 am",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Kochi",
        busNumber: "B1111",
        fromArrival: "07:03 am",
        toArrival: "06:25 am",
      ),
      Bus(
        fromCity: "Indore",
        toCity: "Bangalore",
        busNumber: "B1112",
        fromArrival: "07:22 am",
        toArrival: "07:56 am",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Madurai",
        busNumber: "B1113",
        fromArrival: "05:27 am",
        toArrival: "02:10 pm",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Hyderabad",
        busNumber: "B1114",
        fromArrival: "06:20 am",
        toArrival: "11:33 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Agra",
        busNumber: "B1115",
        fromArrival: "09:43 pm",
        toArrival: "06:57 am",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Goa",
        busNumber: "B1116",
        fromArrival: "05:35 pm",
        toArrival: "04:28 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Bangalore",
        busNumber: "B1117",
        fromArrival: "05:45 pm",
        toArrival: "08:17 am",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Madurai",
        busNumber: "B1118",
        fromArrival: "10:44 pm",
        toArrival: "11:01 am",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Lucknow",
        busNumber: "B1119",
        fromArrival: "09:03 pm",
        toArrival: "02:00 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Trichy",
        busNumber: "B1120",
        fromArrival: "08:38 am",
        toArrival: "06:23 pm",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Delhi",
        busNumber: "B1121",
        fromArrival: "02:18 pm",
        toArrival: "09:16 am",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Surat",
        busNumber: "B1122",
        fromArrival: "10:22 pm",
        toArrival: "02:03 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Jaipur",
        busNumber: "B1123",
        fromArrival: "01:11 pm",
        toArrival: "01:27 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Coimbatore",
        busNumber: "B1124",
        fromArrival: "12:16 pm",
        toArrival: "11:27 am",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Jaipur",
        busNumber: "B1125",
        fromArrival: "03:08 pm",
        toArrival: "07:42 am",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Chennai",
        busNumber: "B1126",
        fromArrival: "02:54 pm",
        toArrival: "09:19 am",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Madurai",
        busNumber: "B1127",
        fromArrival: "07:08 pm",
        toArrival: "07:44 am",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Chandigarh",
        busNumber: "B1128",
        fromArrival: "07:52 am",
        toArrival: "02:09 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Chandigarh",
        busNumber: "B1129",
        fromArrival: "11:44 am",
        toArrival: "02:36 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Indore",
        busNumber: "B1130",
        fromArrival: "07:02 am",
        toArrival: "09:06 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Chandigarh",
        busNumber: "B1131",
        fromArrival: "08:16 am",
        toArrival: "10:54 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Goa",
        busNumber: "B1132",
        fromArrival: "01:23 pm",
        toArrival: "03:19 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Agra",
        busNumber: "B1133",
        fromArrival: "03:35 pm",
        toArrival: "07:14 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Lucknow",
        busNumber: "B1134",
        fromArrival: "09:55 am",
        toArrival: "12:29 pm",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Bangalore",
        busNumber: "B1135",
        fromArrival: "06:07 am",
        toArrival: "05:58 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Mumbai",
        busNumber: "B1136",
        fromArrival: "10:59 pm",
        toArrival: "06:07 am",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Bangalore",
        busNumber: "B1137",
        fromArrival: "06:56 am",
        toArrival: "08:55 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Hyderabad",
        busNumber: "B1138",
        fromArrival: "08:17 pm",
        toArrival: "10:24 pm",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Delhi",
        busNumber: "B1139",
        fromArrival: "02:04 pm",
        toArrival: "05:29 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Agra",
        busNumber: "B1140",
        fromArrival: "08:19 pm",
        toArrival: "11:07 am",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Agra",
        busNumber: "B1141",
        fromArrival: "12:11 pm",
        toArrival: "11:11 am",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Madurai",
        busNumber: "B1142",
        fromArrival: "09:33 am",
        toArrival: "06:47 am",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Chandigarh",
        busNumber: "B1143",
        fromArrival: "10:52 pm",
        toArrival: "06:30 am",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Hyderabad",
        busNumber: "B1144",
        fromArrival: "05:14 am",
        toArrival: "06:24 am",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Nagpur",
        busNumber: "B1145",
        fromArrival: "06:03 am",
        toArrival: "01:53 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Delhi",
        busNumber: "B1146",
        fromArrival: "09:15 am",
        toArrival: "08:20 am",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Agra",
        busNumber: "B1147",
        fromArrival: "05:52 pm",
        toArrival: "10:46 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Madurai",
        busNumber: "B1148",
        fromArrival: "10:08 pm",
        toArrival: "10:38 am",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Lucknow",
        busNumber: "B1149",
        fromArrival: "01:18 pm",
        toArrival: "07:50 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Kochi",
        busNumber: "B1150",
        fromArrival: "01:50 pm",
        toArrival: "09:30 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Kochi",
        busNumber: "B1151",
        fromArrival: "03:25 pm",
        toArrival: "10:43 am",
      ),
      Bus(
        fromCity: "Indore",
        toCity: "Jaipur",
        busNumber: "B1152",
        fromArrival: "09:44 am",
        toArrival: "03:42 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Bangalore",
        busNumber: "B1153",
        fromArrival: "09:17 am",
        toArrival: "05:12 am",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Goa",
        busNumber: "B1154",
        fromArrival: "08:49 pm",
        toArrival: "07:57 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Jaipur",
        busNumber: "B1155",
        fromArrival: "09:32 pm",
        toArrival: "09:27 am",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Lucknow",
        busNumber: "B1156",
        fromArrival: "10:55 am",
        toArrival: "05:24 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Lucknow",
        busNumber: "B1157",
        fromArrival: "01:46 pm",
        toArrival: "05:40 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Trichy",
        busNumber: "B1158",
        fromArrival: "07:01 am",
        toArrival: "09:30 am",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Bangalore",
        busNumber: "B1159",
        fromArrival: "06:02 am",
        toArrival: "08:06 pm",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Surat",
        busNumber: "B1160",
        fromArrival: "05:03 pm",
        toArrival: "05:58 pm",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Patna",
        busNumber: "B1161",
        fromArrival: "02:05 pm",
        toArrival: "07:20 am",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Jaipur",
        busNumber: "B1162",
        fromArrival: "09:01 am",
        toArrival: "07:37 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Goa",
        busNumber: "B1163",
        fromArrival: "05:02 pm",
        toArrival: "01:59 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Nagpur",
        busNumber: "B1164",
        fromArrival: "08:13 am",
        toArrival: "06:30 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Madurai",
        busNumber: "B1165",
        fromArrival: "06:26 am",
        toArrival: "02:45 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Nagpur",
        busNumber: "B1166",
        fromArrival: "04:26 pm",
        toArrival: "06:11 am",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Hyderabad",
        busNumber: "B1167",
        fromArrival: "10:00 am",
        toArrival: "06:32 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Kolkata",
        busNumber: "B1168",
        fromArrival: "06:11 am",
        toArrival: "08:04 am",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Bangalore",
        busNumber: "B1169",
        fromArrival: "09:19 pm",
        toArrival: "08:38 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Patna",
        busNumber: "B1170",
        fromArrival: "10:12 pm",
        toArrival: "12:51 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Hyderabad",
        busNumber: "B1171",
        fromArrival: "05:36 am",
        toArrival: "09:18 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Surat",
        busNumber: "B1172",
        fromArrival: "07:00 pm",
        toArrival: "08:57 am",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Lucknow",
        busNumber: "B1173",
        fromArrival: "07:08 pm",
        toArrival: "11:48 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Kochi",
        busNumber: "B1174",
        fromArrival: "07:43 am",
        toArrival: "06:58 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Jaipur",
        busNumber: "B1175",
        fromArrival: "01:35 pm",
        toArrival: "06:54 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Hyderabad",
        busNumber: "B1176",
        fromArrival: "08:21 pm",
        toArrival: "06:08 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Agra",
        busNumber: "B1177",
        fromArrival: "11:03 am",
        toArrival: "03:49 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Goa",
        busNumber: "B1178",
        fromArrival: "06:29 pm",
        toArrival: "05:09 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Trichy",
        busNumber: "B1179",
        fromArrival: "09:41 am",
        toArrival: "12:37 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Lucknow",
        busNumber: "B1180",
        fromArrival: "06:19 am",
        toArrival: "08:18 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Goa",
        busNumber: "B1181",
        fromArrival: "05:18 pm",
        toArrival: "09:15 am",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Hyderabad",
        busNumber: "B1182",
        fromArrival: "10:06 pm",
        toArrival: "08:00 am",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Kochi",
        busNumber: "B1183",
        fromArrival: "12:01 pm",
        toArrival: "08:36 am",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Hyderabad",
        busNumber: "B1184",
        fromArrival: "09:02 am",
        toArrival: "02:55 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Nagpur",
        busNumber: "B1185",
        fromArrival: "04:56 pm",
        toArrival: "06:16 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Chennai",
        busNumber: "B1186",
        fromArrival: "10:01 am",
        toArrival: "06:37 am",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Bangalore",
        busNumber: "B1187",
        fromArrival: "06:36 am",
        toArrival: "10:59 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Goa",
        busNumber: "B1188",
        fromArrival: "05:17 am",
        toArrival: "11:38 am",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Trichy",
        busNumber: "B1189",
        fromArrival: "10:41 am",
        toArrival: "06:49 am",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Nagpur",
        busNumber: "B1190",
        fromArrival: "02:49 pm",
        toArrival: "07:51 am",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Surat",
        busNumber: "B1191",
        fromArrival: "07:00 am",
        toArrival: "08:49 am",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Trichy",
        busNumber: "B1192",
        fromArrival: "06:43 pm",
        toArrival: "06:57 am",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Jaipur",
        busNumber: "B1193",
        fromArrival: "07:36 pm",
        toArrival: "08:28 am",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Pune",
        busNumber: "B1194",
        fromArrival: "09:30 am",
        toArrival: "03:05 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Surat",
        busNumber: "B1195",
        fromArrival: "09:30 am",
        toArrival: "09:38 am",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Mumbai",
        busNumber: "B1196",
        fromArrival: "01:42 pm",
        toArrival: "03:38 pm",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Kolkata",
        busNumber: "B1197",
        fromArrival: "11:00 am",
        toArrival: "07:35 am",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Surat",
        busNumber: "B1198",
        fromArrival: "06:19 am",
        toArrival: "05:00 am",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Pune",
        busNumber: "B1199",
        fromArrival: "09:28 pm",
        toArrival: "06:11 pm",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Patna",
        busNumber: "B1200",
        fromArrival: "09:27 pm",
        toArrival: "11:19 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Agra",
        busNumber: "B1201",
        fromArrival: "12:49 pm",
        toArrival: "04:51 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Mumbai",
        busNumber: "B1202",
        fromArrival: "01:46 pm",
        toArrival: "08:24 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Nagpur",
        busNumber: "B1203",
        fromArrival: "10:57 am",
        toArrival: "03:39 pm",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Chandigarh",
        busNumber: "B1204",
        fromArrival: "03:27 pm",
        toArrival: "05:57 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Bhopal",
        busNumber: "B1205",
        fromArrival: "05:33 pm",
        toArrival: "01:05 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Pune",
        busNumber: "B1206",
        fromArrival: "06:19 am",
        toArrival: "07:53 am",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Bhopal",
        busNumber: "B1207",
        fromArrival: "05:47 am",
        toArrival: "07:49 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Trichy",
        busNumber: "B1208",
        fromArrival: "02:53 pm",
        toArrival: "03:32 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Bhopal",
        busNumber: "B1209",
        fromArrival: "10:01 pm",
        toArrival: "07:45 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Pune",
        busNumber: "B1210",
        fromArrival: "06:01 pm",
        toArrival: "12:27 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Kolkata",
        busNumber: "B1211",
        fromArrival: "05:19 am",
        toArrival: "09:20 am",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Hyderabad",
        busNumber: "B1212",
        fromArrival: "04:15 pm",
        toArrival: "02:00 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Madurai",
        busNumber: "B1213",
        fromArrival: "09:45 pm",
        toArrival: "05:59 am",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Goa",
        busNumber: "B1214",
        fromArrival: "05:55 am",
        toArrival: "12:35 pm",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Indore",
        busNumber: "B1215",
        fromArrival: "05:23 am",
        toArrival: "10:28 am",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Delhi",
        busNumber: "B1216",
        fromArrival: "01:30 pm",
        toArrival: "10:12 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Jaipur",
        busNumber: "B1217",
        fromArrival: "04:00 pm",
        toArrival: "06:20 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Delhi",
        busNumber: "B1218",
        fromArrival: "11:34 am",
        toArrival: "08:38 pm",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Hyderabad",
        busNumber: "B1219",
        fromArrival: "08:41 am",
        toArrival: "01:27 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Chennai",
        busNumber: "B1220",
        fromArrival: "03:03 pm",
        toArrival: "05:53 am",
      ),
      Bus(
        fromCity: "Indore",
        toCity: "Bhopal",
        busNumber: "B1221",
        fromArrival: "01:33 pm",
        toArrival: "08:39 am",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Nagpur",
        busNumber: "B1222",
        fromArrival: "04:41 pm",
        toArrival: "05:53 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Surat",
        busNumber: "B1223",
        fromArrival: "07:45 pm",
        toArrival: "06:24 pm",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Indore",
        busNumber: "B1224",
        fromArrival: "08:06 pm",
        toArrival: "11:16 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Hyderabad",
        busNumber: "B1225",
        fromArrival: "04:48 pm",
        toArrival: "11:53 am",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Chandigarh",
        busNumber: "B1226",
        fromArrival: "08:13 am",
        toArrival: "05:14 am",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Chandigarh",
        busNumber: "B1227",
        fromArrival: "09:29 am",
        toArrival: "08:25 pm",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Chandigarh",
        busNumber: "B1228",
        fromArrival: "10:44 pm",
        toArrival: "07:48 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Kochi",
        busNumber: "B1229",
        fromArrival: "10:34 am",
        toArrival: "03:36 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Delhi",
        busNumber: "B1230",
        fromArrival: "09:13 pm",
        toArrival: "09:14 am",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Nagpur",
        busNumber: "B1231",
        fromArrival: "06:14 pm",
        toArrival: "05:23 am",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Jaipur",
        busNumber: "B1232",
        fromArrival: "06:54 pm",
        toArrival: "05:38 am",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Chennai",
        busNumber: "B1233",
        fromArrival: "07:44 pm",
        toArrival: "06:38 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Coimbatore",
        busNumber: "B1234",
        fromArrival: "06:27 pm",
        toArrival: "10:37 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Delhi",
        busNumber: "B1235",
        fromArrival: "02:26 pm",
        toArrival: "05:47 am",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Mumbai",
        busNumber: "B1236",
        fromArrival: "02:42 pm",
        toArrival: "05:30 pm",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Goa",
        busNumber: "B1237",
        fromArrival: "04:45 pm",
        toArrival: "10:28 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Delhi",
        busNumber: "B1238",
        fromArrival: "09:41 pm",
        toArrival: "08:05 am",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Madurai",
        busNumber: "B1239",
        fromArrival: "02:40 pm",
        toArrival: "06:28 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Surat",
        busNumber: "B1240",
        fromArrival: "07:15 am",
        toArrival: "11:44 am",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Kochi",
        busNumber: "B1241",
        fromArrival: "07:52 pm",
        toArrival: "03:03 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Delhi",
        busNumber: "B1242",
        fromArrival: "06:29 am",
        toArrival: "10:26 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Bhopal",
        busNumber: "B1243",
        fromArrival: "10:48 am",
        toArrival: "03:01 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Agra",
        busNumber: "B1244",
        fromArrival: "08:42 pm",
        toArrival: "06:37 am",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Mumbai",
        busNumber: "B1245",
        fromArrival: "04:12 pm",
        toArrival: "03:27 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Kolkata",
        busNumber: "B1246",
        fromArrival: "12:51 pm",
        toArrival: "08:52 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Mumbai",
        busNumber: "B1247",
        fromArrival: "08:27 am",
        toArrival: "05:25 am",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Kochi",
        busNumber: "B1248",
        fromArrival: "05:00 pm",
        toArrival: "06:46 pm",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Surat",
        busNumber: "B1249",
        fromArrival: "09:31 am",
        toArrival: "01:39 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Surat",
        busNumber: "B1250",
        fromArrival: "11:56 am",
        toArrival: "09:40 am",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Coimbatore",
        busNumber: "B1251",
        fromArrival: "05:21 am",
        toArrival: "02:14 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Delhi",
        busNumber: "B1252",
        fromArrival: "05:37 am",
        toArrival: "07:10 am",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Coimbatore",
        busNumber: "B1253",
        fromArrival: "09:20 am",
        toArrival: "07:21 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Nagpur",
        busNumber: "B1254",
        fromArrival: "12:21 pm",
        toArrival: "10:07 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Coimbatore",
        busNumber: "B1255",
        fromArrival: "07:17 am",
        toArrival: "10:10 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Kolkata",
        busNumber: "B1256",
        fromArrival: "04:21 pm",
        toArrival: "11:36 am",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Pune",
        busNumber: "B1257",
        fromArrival: "06:20 am",
        toArrival: "09:44 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Chandigarh",
        busNumber: "B1258",
        fromArrival: "06:04 pm",
        toArrival: "04:51 pm",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Coimbatore",
        busNumber: "B1259",
        fromArrival: "12:27 pm",
        toArrival: "09:11 pm",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Chandigarh",
        busNumber: "B1260",
        fromArrival: "07:31 pm",
        toArrival: "11:16 am",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Coimbatore",
        busNumber: "B1261",
        fromArrival: "11:35 am",
        toArrival: "09:03 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Chennai",
        busNumber: "B1262",
        fromArrival: "06:10 am",
        toArrival: "05:27 am",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Chennai",
        busNumber: "B1263",
        fromArrival: "12:32 pm",
        toArrival: "10:44 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Mumbai",
        busNumber: "B1264",
        fromArrival: "05:27 am",
        toArrival: "09:24 am",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Nagpur",
        busNumber: "B1265",
        fromArrival: "07:20 am",
        toArrival: "10:11 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Agra",
        busNumber: "B1266",
        fromArrival: "05:52 am",
        toArrival: "07:12 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Chennai",
        busNumber: "B1267",
        fromArrival: "07:19 am",
        toArrival: "07:59 pm",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Chennai",
        busNumber: "B1268",
        fromArrival: "05:19 pm",
        toArrival: "08:20 am",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Agra",
        busNumber: "B1269",
        fromArrival: "05:12 am",
        toArrival: "10:57 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Jaipur",
        busNumber: "B1270",
        fromArrival: "04:47 pm",
        toArrival: "03:19 pm",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Hyderabad",
        busNumber: "B1271",
        fromArrival: "09:52 pm",
        toArrival: "02:51 pm",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Patna",
        busNumber: "B1272",
        fromArrival: "08:38 pm",
        toArrival: "10:17 am",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Patna",
        busNumber: "B1273",
        fromArrival: "06:50 am",
        toArrival: "04:47 pm",
      ),
      Bus(
        fromCity: "Indore",
        toCity: "Coimbatore",
        busNumber: "B1274",
        fromArrival: "10:53 am",
        toArrival: "10:29 am",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Bhopal",
        busNumber: "B1275",
        fromArrival: "08:14 pm",
        toArrival: "11:30 am",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Chandigarh",
        busNumber: "B1276",
        fromArrival: "07:24 pm",
        toArrival: "06:19 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Chandigarh",
        busNumber: "B1277",
        fromArrival: "07:31 pm",
        toArrival: "10:17 am",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Madurai",
        busNumber: "B1278",
        fromArrival: "01:41 pm",
        toArrival: "01:05 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Hyderabad",
        busNumber: "B1279",
        fromArrival: "09:56 pm",
        toArrival: "11:13 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Hyderabad",
        busNumber: "B1280",
        fromArrival: "04:31 pm",
        toArrival: "12:35 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Lucknow",
        busNumber: "B1281",
        fromArrival: "05:47 pm",
        toArrival: "01:14 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Delhi",
        busNumber: "B1282",
        fromArrival: "06:44 am",
        toArrival: "07:21 am",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Patna",
        busNumber: "B1283",
        fromArrival: "01:47 pm",
        toArrival: "08:53 am",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Bhopal",
        busNumber: "B1284",
        fromArrival: "08:09 am",
        toArrival: "06:23 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Coimbatore",
        busNumber: "B1285",
        fromArrival: "04:33 pm",
        toArrival: "02:58 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Lucknow",
        busNumber: "B1286",
        fromArrival: "09:06 am",
        toArrival: "12:38 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Chandigarh",
        busNumber: "B1287",
        fromArrival: "07:27 pm",
        toArrival: "07:15 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Patna",
        busNumber: "B1288",
        fromArrival: "11:52 am",
        toArrival: "02:41 pm",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Delhi",
        busNumber: "B1289",
        fromArrival: "08:36 pm",
        toArrival: "08:30 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Madurai",
        busNumber: "B1290",
        fromArrival: "10:55 am",
        toArrival: "01:00 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Chennai",
        busNumber: "B1291",
        fromArrival: "03:08 pm",
        toArrival: "10:16 am",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Trichy",
        busNumber: "B1292",
        fromArrival: "04:59 pm",
        toArrival: "11:55 am",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Delhi",
        busNumber: "B1293",
        fromArrival: "09:09 am",
        toArrival: "11:00 am",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Kolkata",
        busNumber: "B1294",
        fromArrival: "08:20 am",
        toArrival: "08:15 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Lucknow",
        busNumber: "B1295",
        fromArrival: "11:49 am",
        toArrival: "06:04 am",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Coimbatore",
        busNumber: "B1296",
        fromArrival: "08:12 pm",
        toArrival: "01:24 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Bangalore",
        busNumber: "B1297",
        fromArrival: "02:43 pm",
        toArrival: "09:10 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Madurai",
        busNumber: "B1298",
        fromArrival: "08:14 am",
        toArrival: "09:32 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Kochi",
        busNumber: "B1299",
        fromArrival: "04:58 pm",
        toArrival: "09:53 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Nagpur",
        busNumber: "B1300",
        fromArrival: "07:02 am",
        toArrival: "04:57 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Pune",
        busNumber: "B1301",
        fromArrival: "11:57 am",
        toArrival: "11:38 am",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Patna",
        busNumber: "B1302",
        fromArrival: "03:42 pm",
        toArrival: "11:11 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Lucknow",
        busNumber: "B1303",
        fromArrival: "09:19 pm",
        toArrival: "03:43 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Goa",
        busNumber: "B1304",
        fromArrival: "09:00 pm",
        toArrival: "02:27 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Jaipur",
        busNumber: "B1305",
        fromArrival: "07:26 pm",
        toArrival: "03:21 pm",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Hyderabad",
        busNumber: "B1306",
        fromArrival: "07:37 am",
        toArrival: "08:48 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Kochi",
        busNumber: "B1307",
        fromArrival: "09:29 am",
        toArrival: "07:13 am",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Trichy",
        busNumber: "B1308",
        fromArrival: "05:25 pm",
        toArrival: "05:08 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Patna",
        busNumber: "B1309",
        fromArrival: "06:34 pm",
        toArrival: "11:23 am",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Bangalore",
        busNumber: "B1310",
        fromArrival: "09:54 am",
        toArrival: "09:16 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Kochi",
        busNumber: "B1311",
        fromArrival: "10:10 am",
        toArrival: "06:27 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Lucknow",
        busNumber: "B1312",
        fromArrival: "01:31 pm",
        toArrival: "05:00 am",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Chandigarh",
        busNumber: "B1313",
        fromArrival: "07:39 pm",
        toArrival: "01:59 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Lucknow",
        busNumber: "B1314",
        fromArrival: "10:58 am",
        toArrival: "02:42 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Goa",
        busNumber: "B1315",
        fromArrival: "02:53 pm",
        toArrival: "01:13 pm",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Trichy",
        busNumber: "B1316",
        fromArrival: "11:15 am",
        toArrival: "10:04 am",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Indore",
        busNumber: "B1317",
        fromArrival: "12:38 pm",
        toArrival: "05:28 am",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Goa",
        busNumber: "B1318",
        fromArrival: "09:16 pm",
        toArrival: "08:22 pm",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Kochi",
        busNumber: "B1319",
        fromArrival: "07:31 pm",
        toArrival: "08:13 am",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Lucknow",
        busNumber: "B1320",
        fromArrival: "05:57 pm",
        toArrival: "12:52 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Chennai",
        busNumber: "B1321",
        fromArrival: "02:57 pm",
        toArrival: "08:46 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Hyderabad",
        busNumber: "B1322",
        fromArrival: "05:39 am",
        toArrival: "02:47 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Kolkata",
        busNumber: "B1323",
        fromArrival: "03:37 pm",
        toArrival: "12:26 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Chandigarh",
        busNumber: "B1324",
        fromArrival: "08:37 am",
        toArrival: "02:07 pm",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Agra",
        busNumber: "B1325",
        fromArrival: "05:16 pm",
        toArrival: "10:01 am",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Lucknow",
        busNumber: "B1326",
        fromArrival: "08:02 am",
        toArrival: "01:44 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Indore",
        busNumber: "B1327",
        fromArrival: "02:06 pm",
        toArrival: "07:50 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Pune",
        busNumber: "B1328",
        fromArrival: "08:13 am",
        toArrival: "03:41 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Bhopal",
        busNumber: "B1329",
        fromArrival: "11:51 am",
        toArrival: "09:39 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Lucknow",
        busNumber: "B1330",
        fromArrival: "05:29 pm",
        toArrival: "06:37 pm",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Lucknow",
        busNumber: "B1331",
        fromArrival: "08:55 am",
        toArrival: "03:17 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Pune",
        busNumber: "B1332",
        fromArrival: "03:18 pm",
        toArrival: "05:44 am",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Surat",
        busNumber: "B1333",
        fromArrival: "08:50 am",
        toArrival: "12:35 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Kolkata",
        busNumber: "B1334",
        fromArrival: "11:44 am",
        toArrival: "09:28 pm",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Hyderabad",
        busNumber: "B1335",
        fromArrival: "09:52 am",
        toArrival: "07:07 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Hyderabad",
        busNumber: "B1336",
        fromArrival: "02:32 pm",
        toArrival: "08:21 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Chandigarh",
        busNumber: "B1337",
        fromArrival: "10:41 pm",
        toArrival: "11:09 am",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Delhi",
        busNumber: "B1338",
        fromArrival: "08:37 am",
        toArrival: "05:22 am",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Delhi",
        busNumber: "B1339",
        fromArrival: "12:43 pm",
        toArrival: "10:09 am",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Lucknow",
        busNumber: "B1340",
        fromArrival: "04:16 pm",
        toArrival: "03:20 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Indore",
        busNumber: "B1341",
        fromArrival: "08:22 pm",
        toArrival: "11:52 am",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Chandigarh",
        busNumber: "B1342",
        fromArrival: "06:17 am",
        toArrival: "06:40 am",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Hyderabad",
        busNumber: "B1343",
        fromArrival: "05:56 pm",
        toArrival: "10:06 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Nagpur",
        busNumber: "B1344",
        fromArrival: "03:21 pm",
        toArrival: "10:15 am",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Pune",
        busNumber: "B1345",
        fromArrival: "02:47 pm",
        toArrival: "08:57 am",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Chandigarh",
        busNumber: "B1346",
        fromArrival: "03:56 pm",
        toArrival: "01:50 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Indore",
        busNumber: "B1347",
        fromArrival: "10:04 am",
        toArrival: "05:56 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Indore",
        busNumber: "B1348",
        fromArrival: "10:07 pm",
        toArrival: "10:48 am",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Nagpur",
        busNumber: "B1349",
        fromArrival: "10:50 am",
        toArrival: "02:59 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Chennai",
        busNumber: "B1350",
        fromArrival: "09:52 am",
        toArrival: "10:00 am",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Delhi",
        busNumber: "B1351",
        fromArrival: "08:24 pm",
        toArrival: "10:10 am",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Nagpur",
        busNumber: "B1352",
        fromArrival: "07:07 pm",
        toArrival: "02:22 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Indore",
        busNumber: "B1353",
        fromArrival: "08:18 pm",
        toArrival: "03:31 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Bangalore",
        busNumber: "B1354",
        fromArrival: "07:23 am",
        toArrival: "01:43 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Hyderabad",
        busNumber: "B1355",
        fromArrival: "02:34 pm",
        toArrival: "09:04 am",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Coimbatore",
        busNumber: "B1356",
        fromArrival: "05:19 am",
        toArrival: "09:40 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Surat",
        busNumber: "B1357",
        fromArrival: "05:22 pm",
        toArrival: "08:40 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Goa",
        busNumber: "B1358",
        fromArrival: "06:16 pm",
        toArrival: "11:58 am",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Indore",
        busNumber: "B1359",
        fromArrival: "06:46 pm",
        toArrival: "08:05 am",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Goa",
        busNumber: "B1360",
        fromArrival: "02:58 pm",
        toArrival: "05:13 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Trichy",
        busNumber: "B1361",
        fromArrival: "03:11 pm",
        toArrival: "10:28 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Patna",
        busNumber: "B1362",
        fromArrival: "05:45 am",
        toArrival: "12:50 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Lucknow",
        busNumber: "B1363",
        fromArrival: "06:53 pm",
        toArrival: "10:54 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Hyderabad",
        busNumber: "B1364",
        fromArrival: "08:59 pm",
        toArrival: "08:45 am",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Coimbatore",
        busNumber: "B1365",
        fromArrival: "05:44 pm",
        toArrival: "09:55 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Pune",
        busNumber: "B1366",
        fromArrival: "04:01 pm",
        toArrival: "06:46 am",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Chandigarh",
        busNumber: "B1367",
        fromArrival: "10:51 am",
        toArrival: "10:24 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Chandigarh",
        busNumber: "B1368",
        fromArrival: "03:57 pm",
        toArrival: "08:24 pm",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Jaipur",
        busNumber: "B1369",
        fromArrival: "06:17 pm",
        toArrival: "11:26 am",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Bangalore",
        busNumber: "B1370",
        fromArrival: "04:48 pm",
        toArrival: "08:09 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Jaipur",
        busNumber: "B1371",
        fromArrival: "11:36 am",
        toArrival: "10:31 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Mumbai",
        busNumber: "B1372",
        fromArrival: "10:26 am",
        toArrival: "06:59 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Madurai",
        busNumber: "B1373",
        fromArrival: "01:29 pm",
        toArrival: "05:21 pm",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Nagpur",
        busNumber: "B1374",
        fromArrival: "02:47 pm",
        toArrival: "11:40 am",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Mumbai",
        busNumber: "B1375",
        fromArrival: "07:51 pm",
        toArrival: "07:38 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Goa",
        busNumber: "B1376",
        fromArrival: "04:52 pm",
        toArrival: "05:29 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Bhopal",
        busNumber: "B1377",
        fromArrival: "06:52 pm",
        toArrival: "09:01 am",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Trichy",
        busNumber: "B1378",
        fromArrival: "04:48 pm",
        toArrival: "10:42 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Indore",
        busNumber: "B1379",
        fromArrival: "02:49 pm",
        toArrival: "09:52 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Delhi",
        busNumber: "B1380",
        fromArrival: "07:43 pm",
        toArrival: "11:01 am",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Indore",
        busNumber: "B1381",
        fromArrival: "03:04 pm",
        toArrival: "06:12 am",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Chennai",
        busNumber: "B1382",
        fromArrival: "05:14 pm",
        toArrival: "06:00 pm",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Trichy",
        busNumber: "B1383",
        fromArrival: "07:59 pm",
        toArrival: "11:48 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Kochi",
        busNumber: "B1384",
        fromArrival: "03:18 pm",
        toArrival: "06:49 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Kolkata",
        busNumber: "B1385",
        fromArrival: "06:38 pm",
        toArrival: "03:44 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Coimbatore",
        busNumber: "B1386",
        fromArrival: "07:03 am",
        toArrival: "09:32 am",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Kolkata",
        busNumber: "B1387",
        fromArrival: "06:40 am",
        toArrival: "11:59 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Bhopal",
        busNumber: "B1388",
        fromArrival: "10:43 pm",
        toArrival: "10:17 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Hyderabad",
        busNumber: "B1389",
        fromArrival: "06:28 pm",
        toArrival: "01:36 pm",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Indore",
        busNumber: "B1390",
        fromArrival: "12:03 pm",
        toArrival: "07:08 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Madurai",
        busNumber: "B1391",
        fromArrival: "04:09 pm",
        toArrival: "07:55 am",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Hyderabad",
        busNumber: "B1392",
        fromArrival: "02:51 pm",
        toArrival: "06:31 pm",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Madurai",
        busNumber: "B1393",
        fromArrival: "11:58 am",
        toArrival: "05:04 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Bangalore",
        busNumber: "B1394",
        fromArrival: "08:11 pm",
        toArrival: "07:07 am",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Kochi",
        busNumber: "B1395",
        fromArrival: "06:35 pm",
        toArrival: "09:56 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Coimbatore",
        busNumber: "B1396",
        fromArrival: "01:22 pm",
        toArrival: "08:17 pm",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Chennai",
        busNumber: "B1397",
        fromArrival: "02:44 pm",
        toArrival: "10:59 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Pune",
        busNumber: "B1398",
        fromArrival: "06:20 pm",
        toArrival: "01:59 pm",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Bangalore",
        busNumber: "B1399",
        fromArrival: "09:09 am",
        toArrival: "01:49 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Delhi",
        busNumber: "B1400",
        fromArrival: "08:31 am",
        toArrival: "10:04 am",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Nagpur",
        busNumber: "B1401",
        fromArrival: "05:16 pm",
        toArrival: "02:27 pm",
      ),
      Bus(
        fromCity: "Chandigarh",
        toCity: "Bangalore",
        busNumber: "B1402",
        fromArrival: "10:29 pm",
        toArrival: "03:39 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Coimbatore",
        busNumber: "B1403",
        fromArrival: "11:57 am",
        toArrival: "07:15 am",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Patna",
        busNumber: "B1404",
        fromArrival: "09:38 am",
        toArrival: "08:41 am",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Nagpur",
        busNumber: "B1405",
        fromArrival: "08:00 am",
        toArrival: "08:13 am",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Pune",
        busNumber: "B1406",
        fromArrival: "10:19 am",
        toArrival: "01:19 pm",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Delhi",
        busNumber: "B1407",
        fromArrival: "08:44 am",
        toArrival: "08:25 am",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Chandigarh",
        busNumber: "B1408",
        fromArrival: "05:00 am",
        toArrival: "10:49 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Bhopal",
        busNumber: "B1409",
        fromArrival: "04:13 pm",
        toArrival: "09:09 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Kochi",
        busNumber: "B1410",
        fromArrival: "07:09 pm",
        toArrival: "10:54 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Patna",
        busNumber: "B1411",
        fromArrival: "04:55 pm",
        toArrival: "07:53 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Mumbai",
        busNumber: "B1412",
        fromArrival: "07:12 pm",
        toArrival: "05:10 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Kochi",
        busNumber: "B1413",
        fromArrival: "02:15 pm",
        toArrival: "11:15 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Pune",
        busNumber: "B1414",
        fromArrival: "09:40 pm",
        toArrival: "05:10 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Surat",
        busNumber: "B1415",
        fromArrival: "04:56 pm",
        toArrival: "01:34 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Lucknow",
        busNumber: "B1416",
        fromArrival: "08:40 am",
        toArrival: "08:46 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Pune",
        busNumber: "B1417",
        fromArrival: "09:57 am",
        toArrival: "06:28 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Coimbatore",
        busNumber: "B1418",
        fromArrival: "08:43 am",
        toArrival: "04:40 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Bangalore",
        busNumber: "B1419",
        fromArrival: "09:11 pm",
        toArrival: "04:28 pm",
      ),
      Bus(
        fromCity: "Indore",
        toCity: "Chennai",
        busNumber: "B1420",
        fromArrival: "05:47 pm",
        toArrival: "07:22 am",
      ),
      Bus(
        fromCity: "Indore",
        toCity: "Kolkata",
        busNumber: "B1421",
        fromArrival: "12:53 pm",
        toArrival: "04:23 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Trichy",
        busNumber: "B1422",
        fromArrival: "09:51 pm",
        toArrival: "03:26 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Agra",
        busNumber: "B1423",
        fromArrival: "03:00 pm",
        toArrival: "06:19 pm",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Patna",
        busNumber: "B1424",
        fromArrival: "10:46 pm",
        toArrival: "08:30 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Chennai",
        busNumber: "B1425",
        fromArrival: "06:58 pm",
        toArrival: "02:20 pm",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Goa",
        busNumber: "B1426",
        fromArrival: "01:35 pm",
        toArrival: "09:26 pm",
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Patna",
        busNumber: "B1427",
        fromArrival: "08:35 am",
        toArrival: "08:25 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Hyderabad",
        busNumber: "B1428",
        fromArrival: "03:16 pm",
        toArrival: "11:07 am",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Chennai",
        busNumber: "B1429",
        fromArrival: "06:52 am",
        toArrival: "06:37 pm",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Pune",
        busNumber: "B1430",
        fromArrival: "01:43 pm",
        toArrival: "01:57 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Kochi",
        busNumber: "B1431",
        fromArrival: "08:35 pm",
        toArrival: "06:33 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Hyderabad",
        busNumber: "B1432",
        fromArrival: "09:03 am",
        toArrival: "12:59 pm",
      ),
      Bus(
        fromCity: "Kolkata",
        toCity: "Kochi",
        busNumber: "B1433",
        fromArrival: "10:51 pm",
        toArrival: "06:42 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Nagpur",
        busNumber: "B1434",
        fromArrival: "06:59 pm",
        toArrival: "10:15 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Bhopal",
        busNumber: "B1435",
        fromArrival: "05:09 pm",
        toArrival: "01:24 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Mumbai",
        busNumber: "B1436",
        fromArrival: "08:29 pm",
        toArrival: "10:58 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Kolkata",
        busNumber: "B1437",
        fromArrival: "12:57 pm",
        toArrival: "09:30 pm",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Kolkata",
        busNumber: "B1438",
        fromArrival: "10:57 am",
        toArrival: "09:33 am",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Goa",
        busNumber: "B1439",
        fromArrival: "08:23 pm",
        toArrival: "09:24 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Patna",
        busNumber: "B1440",
        fromArrival: "10:07 pm",
        toArrival: "09:52 pm",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Kochi",
        busNumber: "B1441",
        fromArrival: "08:31 am",
        toArrival: "10:01 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Kolkata",
        busNumber: "B1442",
        fromArrival: "06:27 pm",
        toArrival: "06:33 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Coimbatore",
        busNumber: "B1443",
        fromArrival: "10:29 am",
        toArrival: "07:28 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Chandigarh",
        busNumber: "B1444",
        fromArrival: "12:16 pm",
        toArrival: "05:34 am",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Kolkata",
        busNumber: "B1445",
        fromArrival: "07:02 pm",
        toArrival: "09:40 pm",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Bangalore",
        busNumber: "B1446",
        fromArrival: "06:37 am",
        toArrival: "10:38 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Lucknow",
        busNumber: "B1447",
        fromArrival: "10:59 am",
        toArrival: "10:23 am",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Nagpur",
        busNumber: "B1448",
        fromArrival: "11:34 am",
        toArrival: "01:57 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Chandigarh",
        busNumber: "B1449",
        fromArrival: "04:23 pm",
        toArrival: "08:06 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Goa",
        busNumber: "B1450",
        fromArrival: "06:03 pm",
        toArrival: "10:47 pm",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Chennai",
        busNumber: "B1451",
        fromArrival: "09:36 pm",
        toArrival: "07:28 pm",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Kochi",
        busNumber: "B1452",
        fromArrival: "04:17 pm",
        toArrival: "11:51 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Delhi",
        busNumber: "B1453",
        fromArrival: "09:39 am",
        toArrival: "10:38 pm",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Trichy",
        busNumber: "B1454",
        fromArrival: "02:36 pm",
        toArrival: "07:32 am",
      ),
      Bus(
        fromCity: "Indore",
        toCity: "Bhopal",
        busNumber: "B1455",
        fromArrival: "10:29 pm",
        toArrival: "06:54 pm",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Lucknow",
        busNumber: "B1456",
        fromArrival: "04:29 pm",
        toArrival: "06:21 pm",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Kochi",
        busNumber: "B1457",
        fromArrival: "08:17 pm",
        toArrival: "09:35 am",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Jaipur",
        busNumber: "B1458",
        fromArrival: "08:22 am",
        toArrival: "06:17 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Chennai",
        busNumber: "B1459",
        fromArrival: "04:30 pm",
        toArrival: "08:49 am",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Goa",
        busNumber: "B1460",
        fromArrival: "09:14 am",
        toArrival: "08:14 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Delhi",
        busNumber: "B1461",
        fromArrival: "06:20 pm",
        toArrival: "07:57 am",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Lucknow",
        busNumber: "B1462",
        fromArrival: "09:01 am",
        toArrival: "08:50 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Lucknow",
        busNumber: "B1463",
        fromArrival: "07:22 am",
        toArrival: "07:28 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Kolkata",
        busNumber: "B1464",
        fromArrival: "04:16 pm",
        toArrival: "06:19 am",
      ),
      Bus(
        fromCity: "Goa",
        toCity: "Chandigarh",
        busNumber: "B1465",
        fromArrival: "02:56 pm",
        toArrival: "04:11 pm",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Coimbatore",
        busNumber: "B1466",
        fromArrival: "09:30 am",
        toArrival: "05:15 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Indore",
        busNumber: "B1467",
        fromArrival: "05:28 am",
        toArrival: "02:59 pm",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Lucknow",
        busNumber: "B1468",
        fromArrival: "09:56 pm",
        toArrival: "09:02 am",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Chandigarh",
        busNumber: "B1469",
        fromArrival: "01:51 pm",
        toArrival: "07:36 pm",
      ),
      Bus(
        fromCity: "Kochi",
        toCity: "Patna",
        busNumber: "B1470",
        fromArrival: "05:19 am",
        toArrival: "10:52 am",
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Mumbai",
        busNumber: "B1471",
        fromArrival: "09:25 pm",
        toArrival: "05:05 pm",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Jaipur",
        busNumber: "B1472",
        fromArrival: "11:19 am",
        toArrival: "02:04 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Coimbatore",
        busNumber: "B1473",
        fromArrival: "01:24 pm",
        toArrival: "01:50 pm",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Goa",
        busNumber: "B1474",
        fromArrival: "07:59 am",
        toArrival: "10:30 am",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Patna",
        busNumber: "B1475",
        fromArrival: "03:05 pm",
        toArrival: "05:48 am",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Agra",
        busNumber: "B1476",
        fromArrival: "02:23 pm",
        toArrival: "05:11 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Indore",
        busNumber: "B1477",
        fromArrival: "11:08 am",
        toArrival: "05:07 am",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Kolkata",
        busNumber: "B1478",
        fromArrival: "10:58 pm",
        toArrival: "06:56 am",
      ),
      Bus(
        fromCity: "Agra",
        toCity: "Coimbatore",
        busNumber: "B1479",
        fromArrival: "05:04 pm",
        toArrival: "01:24 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Agra",
        busNumber: "B1480",
        fromArrival: "06:03 pm",
        toArrival: "09:30 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Trichy",
        busNumber: "B1481",
        fromArrival: "10:07 am",
        toArrival: "02:12 pm",
      ),
      Bus(
        fromCity: "Pune",
        toCity: "Madurai",
        busNumber: "B1482",
        fromArrival: "01:22 pm",
        toArrival: "01:31 pm",
      ),
      Bus(
        fromCity: "Surat",
        toCity: "Coimbatore",
        busNumber: "B1483",
        fromArrival: "01:13 pm",
        toArrival: "04:22 pm",
      ),
      Bus(
        fromCity: "Bhopal",
        toCity: "Delhi",
        busNumber: "B1484",
        fromArrival: "12:27 pm",
        toArrival: "11:01 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Kochi",
        busNumber: "B1485",
        fromArrival: "07:41 am",
        toArrival: "05:13 am",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Jaipur",
        busNumber: "B1486",
        fromArrival: "06:32 am",
        toArrival: "09:16 am",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Coimbatore",
        busNumber: "B1487",
        fromArrival: "06:08 am",
        toArrival: "09:51 pm",
      ),
      Bus(
        fromCity: "Nagpur",
        toCity: "Lucknow",
        busNumber: "B1488",
        fromArrival: "08:45 am",
        toArrival: "08:52 am",
      ),
      Bus(
        fromCity: "Indore",
        toCity: "Lucknow",
        busNumber: "B1489",
        fromArrival: "07:13 am",
        toArrival: "08:41 am",
      ),
      Bus(
        fromCity: "Bangalore",
        toCity: "Patna",
        busNumber: "B1490",
        fromArrival: "07:05 pm",
        toArrival: "06:23 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Surat",
        busNumber: "B1491",
        fromArrival: "03:54 pm",
        toArrival: "08:36 pm",
      ),
      Bus(
        fromCity: "Mumbai",
        toCity: "Pune",
        busNumber: "B1492",
        fromArrival: "04:57 pm",
        toArrival: "01:19 pm",
      ),
      Bus(
        fromCity: "Jaipur",
        toCity: "Madurai",
        busNumber: "B1493",
        fromArrival: "06:55 pm",
        toArrival: "05:57 pm",
      ),
      Bus(
        fromCity: "Patna",
        toCity: "Pune",
        busNumber: "B1494",
        fromArrival: "09:28 am",
        toArrival: "06:31 am",
      ),
      Bus(
        fromCity: "Delhi",
        toCity: "Trichy",
        busNumber: "B1495",
        fromArrival: "08:37 am",
        toArrival: "07:25 pm",
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Madurai",
        busNumber: "B1496",
        fromArrival: "05:59 am",
        toArrival: "05:41 pm",
      ),
      Bus(
        fromCity: "Lucknow",
        toCity: "Delhi",
        busNumber: "B1497",
        fromArrival: "03:42 pm",
        toArrival: "03:02 pm",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Pune",
        busNumber: "B1498",
        fromArrival: "05:44 am",
        toArrival: "12:52 pm",
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Agra",
        busNumber: "B1499",
        fromArrival: "02:02 pm",
        toArrival: "06:46 pm",
      ),
      Bus(
        fromCity: "Hyderabad",
        toCity: "Trichy",
        busNumber: "B1500",
        fromArrival: "05:45 pm",
        toArrival: "12:18 pm",
      ),
    ];
  }
}
