import 'package:flutter/material.dart';
import '../models/bus.dart';

void main() {
  runApp(MaterialApp(debugShowCheckedModeBanner: false, home: BusListPage()));
}

class BusRepository {
  static List<Bus> getBuses() {
    return [
      Bus(
        fromCity: "Chennai",
        toCity: "Tambaram",
        busNumber: "MTC 12B",
        fromArrival: "06:30 AM",
        toArrival: "11:10 PM",
        stops: ["Chennai Central", "Egmore", "Guindy", "Chromepet", "Tambaram"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Koyambedu",
        busNumber: "MTC 27D",
        fromArrival: "07:00 AM",
        toArrival: "07:50 AM",
        stops: ["Adyar", "Saidapet", "T Nagar", "Vadapalani", "Koyambedu"],
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Ooty",
        busNumber: "TNSTC 100A",
        fromArrival: "08:00 AM",
        toArrival: "12:30 PM",
        stops: ["Coimbatore", "Mettupalayam", "Coonoor", "Lovedale", "Ooty"],
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Rameswaram",
        busNumber: "SETC 617",
        fromArrival: "05:00 AM",
        toArrival: "10:45 AM",
        stops: [
          "Madurai Mattuthavani",
          "Paramakudi",
          "Ramanathapuram",
          "Pamban Bridge",
          "Rameswaram",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Vellore",
        busNumber: "SETC 102",
        fromArrival: "06:00 AM",
        toArrival: "10:00 AM",
        stops: ["Chennai Koyambedu", "Sriperumbudur", "Walajapet", "Vellore"],
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Chennai",
        busNumber: "SETC 120",
        fromArrival: "05:30 AM",
        toArrival: "11:30 AM",
        stops: [
          "Trichy Central",
          "Perambalur",
          "Villupuram",
          "Tindivanam",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Salem",
        toCity: "Chennai",
        busNumber: "SETC 300",
        fromArrival: "06:00 AM",
        toArrival: "01:00 PM",
        stops: [
          "Salem",
          "Attur",
          "Villupuram",
          "Tindivanam",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Pondicherry",
        busNumber: "SETC 230",
        fromArrival: "06:30 AM",
        toArrival: "10:00 AM",
        stops: [
          "Chennai Koyambedu",
          "Mahabalipuram",
          "Kalpakkam",
          "Pondicherry",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Trichy",
        busNumber: "SETC 210",
        fromArrival: "09:00 AM",
        toArrival: "03:00 PM",
        stops: [
          "Chennai Koyambedu",
          "Tindivanam",
          "Villupuram",
          "Perambalur",
          "Trichy",
        ],
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Thanjavur",
        busNumber: "TNSTC 44",
        fromArrival: "07:15 AM",
        toArrival: "08:45 AM",
        stops: ["Trichy Central", "Srirangam", "Budalur", "Thanjavur"],
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Chennai",
        busNumber: "SETC 500",
        fromArrival: "09:00 PM",
        toArrival: "06:00 AM",
        stops: [
          "Madurai",
          "Trichy",
          "Villupuram",
          "Tindivanam",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Salem",
        busNumber: "SETC 420",
        fromArrival: "07:00 AM",
        toArrival: "01:00 PM",
        stops: ["Chennai Koyambedu", "Vellore", "Krishnagiri", "Salem"],
      ),
      Bus(
        fromCity: "Tirunelveli",
        toCity: "Chennai",
        busNumber: "SETC 710",
        fromArrival: "05:00 PM",
        toArrival: "05:00 AM",
        stops: [
          "Tirunelveli",
          "Madurai",
          "Trichy",
          "Villupuram",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Erode",
        toCity: "Coimbatore",
        busNumber: "TNSTC 88",
        fromArrival: "09:30 AM",
        toArrival: "11:30 AM",
        stops: ["Erode", "Perundurai", "Avinashi", "Coimbatore"],
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Chidambaram",
        busNumber: "TNSTC 66",
        fromArrival: "06:45 AM",
        toArrival: "10:30 AM",
        stops: ["Trichy", "Ariyalur", "Vridhachalam", "Chidambaram"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Kanyakumari",
        busNumber: "SETC 900",
        fromArrival: "04:00 PM",
        toArrival: "08:00 AM",
        stops: [
          "Chennai Koyambedu",
          "Villupuram",
          "Trichy",
          "Madurai",
          "Tirunelveli",
          "Nagercoil",
          "Kanyakumari",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Hosūr",
        busNumber: "SETC 350",
        fromArrival: "08:00 AM",
        toArrival: "12:30 PM",
        stops: ["Chennai Koyambedu", "Vellore", "Krishnagiri", "Hosūr"],
      ),
      Bus(
        fromCity: "Salem",
        toCity: "Namakkal",
        busNumber: "TNSTC 77",
        fromArrival: "07:30 AM",
        toArrival: "09:00 AM",
        stops: ["Salem", "Rasipuram", "Namakkal"],
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Dindigul",
        busNumber: "TNSTC 55",
        fromArrival: "08:00 AM",
        toArrival: "09:30 AM",
        stops: ["Madurai", "Sholavandan", "Dindigul"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Tirupati",
        busNumber: "SETC 777",
        fromArrival: "06:00 AM",
        toArrival: "11:00 AM",
        stops: ["Chennai Koyambedu", "Tiruvallur", "Tiruttani", "Tirupati"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Trichy",
        busNumber: "SETC 101",
        fromArrival: "06:00 AM",
        toArrival: "11:30 AM",
        stops: [
          "Chennai Koyambedu",
          "Villupuram",
          "Vriddhachalam",
          "Perambalur",
          "Trichy",
        ],
      ),
      Bus(
        fromCity: "Trichy",
        toCity: "Chennai",
        busNumber: "SETC 102",
        fromArrival: "02:00 PM",
        toArrival: "08:00 PM",
        stops: [
          "Trichy",
          "Perambalur",
          "Vriddhachalam",
          "Villupuram",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Madurai",
        busNumber: "SETC 103",
        fromArrival: "09:00 AM",
        toArrival: "04:00 PM",
        stops: [
          "Chennai Koyambedu",
          "Villupuram",
          "Trichy",
          "Dindigul",
          "Madurai",
        ],
      ),
      Bus(
        fromCity: "Madurai",
        toCity: "Chennai",
        busNumber: "SETC 104",
        fromArrival: "09:00 PM",
        toArrival: "04:30 AM",
        stops: [
          "Madurai",
          "Dindigul",
          "Trichy",
          "Villupuram",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Coimbatore",
        busNumber: "SETC 105",
        fromArrival: "08:00 PM",
        toArrival: "06:00 AM",
        stops: [
          "Chennai Koyambedu",
          "Villupuram",
          "Salem",
          "Erode",
          "Coimbatore",
        ],
      ),
      Bus(
        fromCity: "Coimbatore",
        toCity: "Chennai",
        busNumber: "SETC 106",
        fromArrival: "09:00 PM",
        toArrival: "07:00 AM",
        stops: [
          "Coimbatore",
          "Erode",
          "Salem",
          "Villupuram",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Tirunelveli",
        busNumber: "SETC 107",
        fromArrival: "05:00 PM",
        toArrival: "05:30 AM",
        stops: [
          "Chennai Koyambedu",
          "Villupuram",
          "Trichy",
          "Madurai",
          "Tirunelveli",
        ],
      ),
      Bus(
        fromCity: "Tirunelveli",
        toCity: "Chennai",
        busNumber: "SETC 108",
        fromArrival: "06:00 PM",
        toArrival: "06:00 AM",
        stops: [
          "Tirunelveli",
          "Madurai",
          "Trichy",
          "Villupuram",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Nagercoil",
        busNumber: "SETC 109",
        fromArrival: "04:30 PM",
        toArrival: "06:00 AM",
        stops: [
          "Chennai Koyambedu",
          "Villupuram",
          "Madurai",
          "Tirunelveli",
          "Nagercoil",
        ],
      ),
      Bus(
        fromCity: "Nagercoil",
        toCity: "Chennai",
        busNumber: "SETC 110",
        fromArrival: "05:00 PM",
        toArrival: "06:00 AM",
        stops: [
          "Nagercoil",
          "Tirunelveli",
          "Madurai",
          "Villupuram",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Rameswaram",
        busNumber: "SETC 111",
        fromArrival: "03:00 PM",
        toArrival: "05:30 AM",
        stops: [
          "Chennai Koyambedu",
          "Villupuram",
          "Trichy",
          "Ramanathapuram",
          "Rameswaram",
        ],
      ),
      Bus(
        fromCity: "Rameswaram",
        toCity: "Chennai",
        busNumber: "SETC 112",
        fromArrival: "04:00 PM",
        toArrival: "06:00 AM",
        stops: [
          "Rameswaram",
          "Ramanathapuram",
          "Trichy",
          "Villupuram",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Salem",
        busNumber: "SETC 113",
        fromArrival: "06:00 AM",
        toArrival: "12:00 PM",
        stops: ["Chennai Koyambedu", "Villupuram", "Vriddhachalam", "Salem"],
      ),
      Bus(
        fromCity: "Salem",
        toCity: "Chennai",
        busNumber: "SETC 114",
        fromArrival: "02:00 PM",
        toArrival: "08:00 PM",
        stops: ["Salem", "Vriddhachalam", "Villupuram", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Erode",
        busNumber: "SETC 115",
        fromArrival: "10:00 PM",
        toArrival: "05:30 AM",
        stops: ["Chennai Koyambedu", "Villupuram", "Salem", "Erode"],
      ),
      Bus(
        fromCity: "Erode",
        toCity: "Chennai",
        busNumber: "SETC 116",
        fromArrival: "09:30 PM",
        toArrival: "05:00 AM",
        stops: ["Erode", "Salem", "Villupuram", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Kanyakumari",
        busNumber: "SETC 117",
        fromArrival: "03:00 PM",
        toArrival: "07:00 AM",
        stops: [
          "Chennai Koyambedu",
          "Villupuram",
          "Madurai",
          "Nagercoil",
          "Kanyakumari",
        ],
      ),
      Bus(
        fromCity: "Kanyakumari",
        toCity: "Chennai",
        busNumber: "SETC 118",
        fromArrival: "04:00 PM",
        toArrival: "08:00 AM",
        stops: [
          "Kanyakumari",
          "Nagercoil",
          "Madurai",
          "Villupuram",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Karaikudi",
        busNumber: "SETC 119",
        fromArrival: "07:00 AM",
        toArrival: "02:00 PM",
        stops: [
          "Chennai Koyambedu",
          "Villupuram",
          "Trichy",
          "Pudukkottai",
          "Karaikudi",
        ],
      ),
      Bus(
        fromCity: "Karaikudi",
        toCity: "Chennai",
        busNumber: "SETC 120",
        fromArrival: "02:00 PM",
        toArrival: "09:00 PM",
        stops: [
          "Karaikudi",
          "Pudukkottai",
          "Trichy",
          "Villupuram",
          "Chennai Koyambedu",
        ],
      ),

      // Continuing inside getBuses()
      Bus(
        fromCity: "Chennai",
        toCity: "Thanjavur",
        busNumber: "SETC 121",
        fromArrival: "06:30 AM",
        toArrival: "01:00 PM",
        stops: ["Chennai Koyambedu", "Villupuram", "Trichy", "Thanjavur"],
      ),
      Bus(
        fromCity: "Thanjavur",
        toCity: "Chennai",
        busNumber: "SETC 122",
        fromArrival: "02:00 PM",
        toArrival: "08:30 PM",
        stops: ["Thanjavur", "Trichy", "Villupuram", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Pondicherry",
        busNumber: "SETC 123",
        fromArrival: "07:00 AM",
        toArrival: "11:00 AM",
        stops: [
          "Chennai Koyambedu",
          "Mahabalipuram",
          "Kalpakkam",
          "Pondicherry",
        ],
      ),
      Bus(
        fromCity: "Pondicherry",
        toCity: "Chennai",
        busNumber: "SETC 124",
        fromArrival: "04:00 PM",
        toArrival: "08:00 PM",
        stops: [
          "Pondicherry",
          "Kalpakkam",
          "Mahabalipuram",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Villupuram",
        busNumber: "SETC 125",
        fromArrival: "05:00 AM",
        toArrival: "09:00 AM",
        stops: ["Chennai Koyambedu", "Tindivanam", "Villupuram"],
      ),
      Bus(
        fromCity: "Villupuram",
        toCity: "Chennai",
        busNumber: "SETC 126",
        fromArrival: "02:00 PM",
        toArrival: "06:00 PM",
        stops: ["Villupuram", "Tindivanam", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Vellore",
        busNumber: "SETC 127",
        fromArrival: "06:00 AM",
        toArrival: "09:30 AM",
        stops: ["Chennai Koyambedu", "Sriperumbudur", "Walajapet", "Vellore"],
      ),
      Bus(
        fromCity: "Vellore",
        toCity: "Chennai",
        busNumber: "SETC 128",
        fromArrival: "05:00 PM",
        toArrival: "08:30 PM",
        stops: ["Vellore", "Walajapet", "Sriperumbudur", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Krishnagiri",
        busNumber: "SETC 129",
        fromArrival: "07:30 AM",
        toArrival: "01:00 PM",
        stops: ["Chennai Koyambedu", "Vellore", "Ambur", "Krishnagiri"],
      ),
      Bus(
        fromCity: "Krishnagiri",
        toCity: "Chennai",
        busNumber: "SETC 130",
        fromArrival: "03:00 PM",
        toArrival: "08:30 PM",
        stops: ["Krishnagiri", "Ambur", "Vellore", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Dharmapuri",
        busNumber: "SETC 131",
        fromArrival: "08:00 AM",
        toArrival: "01:30 PM",
        stops: ["Chennai Koyambedu", "Vellore", "Krishnagiri", "Dharmapuri"],
      ),
      Bus(
        fromCity: "Dharmapuri",
        toCity: "Chennai",
        busNumber: "SETC 132",
        fromArrival: "04:00 PM",
        toArrival: "09:30 PM",
        stops: ["Dharmapuri", "Krishnagiri", "Vellore", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Tiruppur",
        busNumber: "SETC 133",
        fromArrival: "09:00 PM",
        toArrival: "06:00 AM",
        stops: ["Chennai Koyambedu", "Salem", "Erode", "Tiruppur"],
      ),
      Bus(
        fromCity: "Tiruppur",
        toCity: "Chennai",
        busNumber: "SETC 134",
        fromArrival: "10:00 PM",
        toArrival: "07:00 AM",
        stops: ["Tiruppur", "Erode", "Salem", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Karur",
        busNumber: "SETC 135",
        fromArrival: "05:30 AM",
        toArrival: "12:00 PM",
        stops: ["Chennai Koyambedu", "Villupuram", "Trichy", "Karur"],
      ),
      Bus(
        fromCity: "Karur",
        toCity: "Chennai",
        busNumber: "SETC 136",
        fromArrival: "01:00 PM",
        toArrival: "07:30 PM",
        stops: ["Karur", "Trichy", "Villupuram", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Nagapattinam",
        busNumber: "SETC 137",
        fromArrival: "06:00 AM",
        toArrival: "01:30 PM",
        stops: ["Chennai Koyambedu", "Cuddalore", "Karaikal", "Nagapattinam"],
      ),
      Bus(
        fromCity: "Nagapattinam",
        toCity: "Chennai",
        busNumber: "SETC 138",
        fromArrival: "02:00 PM",
        toArrival: "08:30 PM",
        stops: ["Nagapattinam", "Karaikal", "Cuddalore", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Tuticorin",
        busNumber: "SETC 139",
        fromArrival: "04:00 PM",
        toArrival: "05:00 AM",
        stops: ["Chennai Koyambedu", "Villupuram", "Madurai", "Tuticorin"],
      ),
      Bus(
        fromCity: "Tuticorin",
        toCity: "Chennai",
        busNumber: "SETC 140",
        fromArrival: "06:00 PM",
        toArrival: "07:00 AM",
        stops: ["Tuticorin", "Madurai", "Villupuram", "Chennai Koyambedu"],
      ),

      Bus(
        fromCity: "Chennai",
        toCity: "Dindigul",
        busNumber: "SETC 141",
        fromArrival: "07:00 AM",
        toArrival: "02:00 PM",
        stops: ["Chennai Koyambedu", "Villupuram", "Trichy", "Dindigul"],
      ),
      Bus(
        fromCity: "Dindigul",
        toCity: "Chennai",
        busNumber: "SETC 142",
        fromArrival: "03:00 PM",
        toArrival: "10:00 PM",
        stops: ["Dindigul", "Trichy", "Villupuram", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Cuddalore",
        busNumber: "SETC 143",
        fromArrival: "05:00 AM",
        toArrival: "09:00 AM",
        stops: ["Chennai Koyambedu", "Tindivanam", "Cuddalore"],
      ),
      Bus(
        fromCity: "Cuddalore",
        toCity: "Chennai",
        busNumber: "SETC 144",
        fromArrival: "05:00 PM",
        toArrival: "09:00 PM",
        stops: ["Cuddalore", "Tindivanam", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Kumbakonam",
        busNumber: "SETC 145",
        fromArrival: "06:00 AM",
        toArrival: "12:00 PM",
        stops: ["Chennai Koyambedu", "Villupuram", "Ariyalur", "Kumbakonam"],
      ),
      Bus(
        fromCity: "Kumbakonam",
        toCity: "Chennai",
        busNumber: "SETC 146",
        fromArrival: "01:30 PM",
        toArrival: "07:30 PM",
        stops: ["Kumbakonam", "Ariyalur", "Villupuram", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Mayiladuthurai",
        busNumber: "SETC 147",
        fromArrival: "07:00 AM",
        toArrival: "01:00 PM",
        stops: [
          "Chennai Koyambedu",
          "Villupuram",
          "Cuddalore",
          "Mayiladuthurai",
        ],
      ),
      Bus(
        fromCity: "Mayiladuthurai",
        toCity: "Chennai",
        busNumber: "SETC 148",
        fromArrival: "02:00 PM",
        toArrival: "08:00 PM",
        stops: [
          "Mayiladuthurai",
          "Cuddalore",
          "Villupuram",
          "Chennai Koyambedu",
        ],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Chidambaram",
        busNumber: "SETC 149",
        fromArrival: "06:30 AM",
        toArrival: "11:00 AM",
        stops: ["Chennai Koyambedu", "Tindivanam", "Cuddalore", "Chidambaram"],
      ),
      Bus(
        fromCity: "Chidambaram",
        toCity: "Chennai",
        busNumber: "SETC 150",
        fromArrival: "03:00 PM",
        toArrival: "07:30 PM",
        stops: ["Chidambaram", "Cuddalore", "Tindivanam", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Sivakasi",
        busNumber: "SETC 151",
        fromArrival: "05:00 PM",
        toArrival: "06:00 AM",
        stops: ["Chennai Koyambedu", "Villupuram", "Madurai", "Sivakasi"],
      ),
      Bus(
        fromCity: "Sivakasi",
        toCity: "Chennai",
        busNumber: "SETC 152",
        fromArrival: "06:00 PM",
        toArrival: "07:00 AM",
        stops: ["Sivakasi", "Madurai", "Villupuram", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Rajapalayam",
        busNumber: "SETC 153",
        fromArrival: "04:30 PM",
        toArrival: "06:00 AM",
        stops: ["Chennai Koyambedu", "Villupuram", "Madurai", "Rajapalayam"],
      ),
      Bus(
        fromCity: "Rajapalayam",
        toCity: "Chennai",
        busNumber: "SETC 154",
        fromArrival: "05:30 PM",
        toArrival: "07:00 AM",
        stops: ["Rajapalayam", "Madurai", "Villupuram", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Virudhunagar",
        busNumber: "SETC 155",
        fromArrival: "06:00 PM",
        toArrival: "06:30 AM",
        stops: ["Chennai Koyambedu", "Villupuram", "Madurai", "Virudhunagar"],
      ),
      Bus(
        fromCity: "Virudhunagar",
        toCity: "Chennai",
        busNumber: "SETC 156",
        fromArrival: "07:00 PM",
        toArrival: "07:30 AM",
        stops: ["Virudhunagar", "Madurai", "Villupuram", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Namakkal",
        busNumber: "SETC 157",
        fromArrival: "05:30 AM",
        toArrival: "12:00 PM",
        stops: ["Chennai Koyambedu", "Villupuram", "Salem", "Namakkal"],
      ),
      Bus(
        fromCity: "Namakkal",
        toCity: "Chennai",
        busNumber: "SETC 158",
        fromArrival: "02:00 PM",
        toArrival: "08:30 PM",
        stops: ["Namakkal", "Salem", "Villupuram", "Chennai Koyambedu"],
      ),
      Bus(
        fromCity: "Chennai",
        toCity: "Perambalur",
        busNumber: "SETC 159",
        fromArrival: "07:00 AM",
        toArrival: "12:30 PM",
        stops: [
          "Chennai Koyambedu",
          "Villupuram",
          "Vriddhachalam",
          "Perambalur",
        ],
      ),
      Bus(
        fromCity: "Perambalur",
        toCity: "Chennai",
        busNumber: "SETC 160",
        fromArrival: "03:00 PM",
        toArrival: "08:30 PM",
        stops: [
          "Perambalur",
          "Vriddhachalam",
          "Villupuram",
          "Chennai Koyambedu",
        ],
      ),

      // You can keep adding more TN routes here, following the same structure

      // Example: Chennai <-> Villupuram, Villupuram <-> Thanjavur, Coimbatore <-> Madurai, etc.
    ];
  }
}

// ------------------ Bus List Page ------------------
class BusListPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final buses = BusRepository.getBuses();

    return Scaffold(
      appBar: AppBar(title: Text("Available Buses")),
      body: ListView.builder(
        itemCount: buses.length,
        itemBuilder: (context, index) {
          final bus = buses[index];
          return Card(
            margin: EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            child: ListTile(
              leading: Icon(Icons.directions_bus, color: Colors.orange),
              title: Text("Bus: ${bus.busNumber}"),
              subtitle: Text(
                "${bus.fromCity} → ${bus.toCity}\n"
                "Departure: ${bus.fromArrival}, Arrival: ${bus.toArrival}",
              ),
              isThreeLine: true,
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(builder: (_) => BusDetailPage(bus: bus)),
                );
              },
            ),
          );
        },
      ),
    );
  }
}

// ------------------ Bus Detail Page ------------------
class BusDetailPage extends StatelessWidget {
  final Bus bus;

  const BusDetailPage({super.key, required this.bus});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("Bus ${bus.busNumber} Details")),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              "${bus.fromCity} → ${bus.toCity}",
              style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
            ),
            SizedBox(height: 10),
            Text(
              "Departure: ${bus.fromArrival} | Arrival: ${bus.toArrival}",
              style: TextStyle(fontSize: 16),
            ),
            Divider(height: 30, thickness: 2),

            // Timeline of Stops
            Expanded(
              child: ListView.builder(
                itemCount: bus.stops.length,
                itemBuilder: (context, index) {
                  final stop = bus.stops[index];
                  return ListTile(
                    leading: Icon(Icons.location_on, color: Colors.blue),
                    title: Text(stop),
                    subtitle: Text(
                      index == 0
                          ? "Start Point"
                          : (index == bus.stops.length - 1
                              ? "Destination"
                              : "Via Stop"),
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}
