name: ptransit
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  geolocator: ^13.0.4
  firebase_database: ^12.0.1

  # State Management
  provider: ^6.1.2

  # Device & Connectivity
  connectivity_plus: ^7.0.0
  location: ^8.0.1

  # Utilities
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2

  # Authentication & Input
  sms_autofill: ^2.3.0

  # Voice / Speech
  speech_to_text: ^7.3.0
  flutter_tts: ^4.0.2

  # Firebase
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1

  # Maps
  google_maps_flutter: ^2.10.0

  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/nk7sih.jpg"
  adaptive_icon_background: "#ffffff" # background color (Android)
  adaptive_icon_foreground: "assets/nk7sih.jpg"

flutter:
  uses-material-design: true

  # Uncomment and add assets when needed
assets:
  - assets/
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: assets/fonts/YourFont.ttf
